(library
 (name ocaml_mutants_engine)
 (libraries
  ocaml_mutants_core
  csexp
  otoml
  fpath
  fmt
  logs
  mtime
  mtime.clock.os
  ptime
  unix
  threads
  compiler-libs.common
  digestif
  yojson
  matrix
  mosaic)
 (foreign_stubs
  (language c)
  (names process_stubs signal_stubs dir_cap_stubs terminal_stubs)))
